# Generated by Django 4.1.2 on 2022-10-24 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="user",
            new_name="critic",
        ),
    ]
